### ISSUE TITLE
Add tensorflow to dependencies

### ISSUE THREAD

**Issue by he-sk** [nebulastream/nebulastream-dependencies#19]
We need to ship tensorflow dependencies if we want to merge https://github.com/nebulastream/nebulastream/issues/1779.

**Comment by keyseven123** [comment]
@he-sk so I think that this issue can be closed as I adapted the github docker build files in the PR https://github.com/nebulastream/nebulastream/pull/2635.

**Comment by he-sk** [comment]
@keyseven123 How do you install TF on a developer machine? Is that done in CMakeLists.txt or do you have to install a OS package?

**Comment by keyseven123** [comment]
So in the meeting last week, the consents was that each developer machine has TF installed system wide. You can do this by following the steps in the docker build files, e.g. line 33 to 47 in `Dockerfile-NES-Build-ubuntu-20_04`.

**Comment by he-sk** [comment]
Isn't there a way to use an OS package instead of building manually?

**Comment by keyseven123** [comment]
I could not find anything online to just get tensorflow-lite.

**Comment by he-sk** [comment]
Would it work with complete TF? That is still easier for a developer to install, isn't it?

**Comment by keyseven123** [comment]
N it would not, as the includes are different.

**Comment by keyseven123** [comment]
I will update the documentation.
