### ISSUE TITLE
Remove LLVM from dependencies

### ISSUE THREAD

**Issue by PhilippGrulich** [nebulastream/nebulastream-dependencies#29]
The LLVM port in vcpkg is quite unstable and out-of-date. To this end, I suggest to maintain our pre-build llvm in a seperate repo  https://github.com/nebulastream/clang-binaries. Thus we can remove llvm from vcpkg.

**Comment by alepping** [comment]
LLVM was removed from our dependencies. We are building it ourselves now (version 16 currently).
